### ISSUE TITLE
Add attribute notation to SearchableTrait

### ISSUE THREAD

**Issue by jurv** [monsieurbiz/SyliusSearchPlugin#198]
The SearchableTrait only has annotations for Doctrine, which is an issue for projects where Doctrine is configured to use PHP attributes: 

```yaml
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    App:
                        type: attribute
                        [...]
```
When following the installation instructions with this configuration, the `console doctrine:migrations:diff` step doesn't generate any migration, as no changes are detected.

The configuration provided in the annotations should also be provided as PHP attributes.
