### ISSUE TITLE
Taxon products index page without filters

### ISSUE THREAD

**Issue by easycom-xmedias** [monsieurbiz/SyliusSearchPlugin#51]
After installation of plugin, everything works like a charm, except the taxon produtcs index that do not contain filters.

**Origin:** conflict between both Sylius core (sylius_shop_product_index) and plugin (monsieurbiz_sylius_search_taxon) routes.

```
$ ./bin/console debug:router | grep "taxons/{slug}" 
sylius_shop_product_index                 GET        ANY      ANY    /{_locale}/taxons/{slug}
monsieurbiz_sylius_search_taxon      GET         ANY      ANY    /{_locale}/taxons/{slug}
```

**Workaround 1 (KO in my studied case):** make Sylius core route never used (by redefining `sylius_shop_product_index` with `condition: "1 == 0"`). This solution leads to some side effects (this route is called in many templates)

**Workaround 2 (OK):** overriding `sylius_shop_product_index` with same definition than the `monsieurbiz_sylius_search_taxon` route one.
```
sylius_shop_product_index:
  path: /taxons/{slug}
  methods: [ GET ]
  defaults:
    _controller: ...
  requirements:
    slug: .+
```

Is another solution ?
