### ISSUE TITLE
Ability to define a different index name

### ISSUE THREAD

**Issue by armellarcier** [monsieurbiz/SyliusSearchPlugin#69]
Right now the base index name is defined as `"documents"` in a constant `DOCUMENT_INDEX_NAME` in the `AbstractIndex` class.

We need to use different index names because one elasticsearch server will serve multiple sylius websites.

Maybe the documentation could suggest a way of doing that.

Maybe it should be a configuration parameter.

Should we just decorate `AbstractIndex` ?

**Comment by rwch** [comment]
Although there is no possibility to change the index name, the index can be prefixed, which should be enough in many cases:

config/services.yaml (elastically_index_prefix):
```
JoliCode\Elastically\Client:
        arguments:
            $config:
                host: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_HOST)%'
                port: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_PORT)%'
                elastically_mappings_directory: '%kernel.project_dir%/config/packages/monsieurbiz/syliusSearchPlugin/mappings'
                elastically_index_prefix: '%env(MONSIEURBIZ_SEARCHPLUGIN_INDEX_PREFIX)%'
```
